name: mono_app
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - apps/app_boilerplate
  - apps/client_example
  - packages/core
  - packages/design_system
  - packages/shared
  - packages/modules/auth
  - packages/modules/home
  - packages/modules/user_profile
  - packages/features/auth_flow
  - packages/features/home_flow
  - packages/features/onboarding
  - packages/features/profile_flow

dev_dependencies:
  melos: ^6.3.0
  flutter_lints: ^5.0.0
