name: user_profile_module
description: User profile domain module - entities, repositories, use cases, data
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
