name: app_boilerplate
description: Boilerplate app - base for all client apps
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Workspace packages
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  shared:
    path: ../../packages/shared
  auth_module:
    path: ../../packages/modules/auth
  home_module:
    path: ../../packages/modules/home
  user_profile_module:
    path: ../../packages/modules/user_profile
  auth_flow:
    path: ../../packages/features/auth_flow
  home_flow:
    path: ../../packages/features/home_flow
  onboarding:
    path: ../../packages/features/onboarding
  profile_flow:
    path: ../../packages/features/profile_flow

  # State & DI
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Routing
  auto_route: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.4.0
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  generate: true
